### ISSUE TITLE
 Failed to create remote connection

### ISSUE THREAD

**Issue by w22gb8** [database64128/shadowsocks-go#53] opened 2024-01-09 08:26 UTC
服务器提示错误：
```
2024-01-09T16:22:23.584+0800 WARN service/tcp.go:238 Failed to create remote connection
 {"server": "ss-2022", "listener": 0, "listenAddress": "[::]:2022", "clientAddress": "[::ffff:xxxx]:14124", 
"username": "", "targetAddress": "xxxxx:80",
 "client": "direct", "initialPayloadLength": 136, "error": "dial tcp xxxx:80: setsockopt: operation not supported"}
```
server：
```json
{
  "servers": [
    {
      "name": "ss-2022",
      "listen": ":2022",
      "protocol": "2022-blake3-aes-128-gcm",
      "enableTCP": true,
      "listenerTFO": false,
      "enableUDP": true,
      "mtu": 1500,
      "unsafeRequestStreamPrefix": "UEAQ1vadNGxkAn1wOOBs7oJdhrLEjtMSMrw3f5DTWig=",
      "unsafeResponseStreamPrefix": "OWMAFigHD7hesPPrr54iESnFp0t3LxuAEAztkaQwo84=",
      "psk": "t4mTVqHeTVYsTTYouAJwMg=="
    }
  ]
}
```
client:
```json
{
   "servers": [
      {
         "name": "socks5",
         "listen": ":1080",
         "protocol": "socks5",
         "enableTCP": true,
         "listenerTFO": false,
         "enableUDP": true,
         "mtu": 1500
      }
   ],
   "clients": [
      {
         "name": "ss-2022",
         "endpoint": "xxxx:2022",
         "protocol": "2022-blake3-aes-128-gcm",
         "enableTCP": true,
         "dialerTFO": false,
         "enableUDP": true,
         "mtu": 1500,
         "unsafeRequestStreamPrefix": "UEAQ1vadNGxkAn1wOOBs7oJdhrLEjtMSMrw3f5DTWig=",
         "unsafeResponseStreamPrefix": "OWMAFigHD7hesPPrr54iESnFp0t3LxuAEAztkaQwo84=",
         "psk": "t4mTVqHeTVYsTTYouAJwMg=="
      }
   ]
}
```

**Comment by database64128** [comment] 2024-01-09 08:41
Likely duplicate of #29.

**Closed as completed** 2024-01-09 08:46 UTC
